AWSTemplateFormatVersion: '2010-09-09'
Description: Template to Create an IAM Role
Parameters:
     CompromisedInstanceAccount:
      Type: String
      Description: Enter the account no of the compromised account
Resources:
  LambdaAssumerolepolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: Lambda assume role policy for compromised instance account
      ManagedPolicyName: 
        Fn::Sub: Assume-Role-Policy-Account-${CompromisedInstanceAccount}
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource:
              - Fn::Sub: 'arn:aws-cn:iam::${CompromisedInstanceAccount}:role/LambdaAssumeRole'
      Roles: 
        - LambdaIncidentResponseRole
              
